server:
  port: 9001

spring:
  threads:
    virtual:
      enabled: true

  mvc:
    throw-exception-if-no-handler-found: true
    log-request-details: true
  web:
    resources:
      add-mappings: false

  datasource:
    url: jdbc:postgresql://localhost:5433/auth
    username: auth
    password: authpassword
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 80
      minimum-idle: 80
      connection-timeout: 2000

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

session:
  expiration: 3600

management:
  # Individual endpoint settings (singular)
  endpoint:
    health:
      show-details: always
      group:
        liveness:
          show-details: always
        readiness:
          show-details: always
        custom:
          include: [db, ssl]
    env:
      show-values: always
    configprops:
      show-values: always

  # Global exposure settings (plural)
  endpoints:
    web:
      exposure:
        include: "*"

  metrics:
    tags:
      application: auth
  info:
    env:
      enabled: true

logging:
  level:
    com.onlineshop.auth: INFO
    org.springframework.web: TRACE
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
